apiVersion: {{ include "greenscout-backend.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "greenscout-backend.fullname" . }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "greenscout-backend.labels" . | nindent 4 }}
spec:
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "greenscout-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "greenscout-backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "greenscout-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          
          volumeMounts:
          # Credentials volume mount
          {{- if .Values.secrets.enabled }}
          - name: secrets
            mountPath: "{{ .Values.secrets.mountPath }}"
            subPath: {{ .Values.secrets.key | default "credentials.json" }}
            readOnly: true
          {{- end }}
          # ConfigMap volume mount
          {{- if .Values.configMap.enabled }}
          - name: config
            mountPath: "{{ .Values.configMap.mountPath }}"
            subPath: {{ .Values.configMap.key | default "greenscout-backend.config.yaml" }}
            readOnly: true
          {{- end }}
          ## Resources
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  
      volumes:
        {{- if .Values.secrets.enabled }}
        - name: secrets
          secret:
            secretName: {{ .Values.secrets.secretName }}
            items:
              - key: {{ .Values.secrets.credentalsKey | default "credentials.json" }}
                path: "/run/credentials.json"
              - key: {{ .Values.secrets.configsKey | default "greenscout.config.yaml" }}
                path: "/greenscout.config.yaml"
              - key: {{ .Values.secrets.tokenKey | default "token.json" }}
                path: "/run/token.json"
        {{- end }}
      